export enum TransitionTypes {
    Enter = 1,
    Exit = 2,
    Both = 4
  }
  
export enum PerimeterErrors {
    GEOFENCING_UNAVAILABLE,
    CLIENT_UNINITIALIZED,
    GENERIC_PLATFORM_ERROR,
    INCORRECT_PERMISSIONS,
    FOREGROUND_DENIED,
    INVALID_FENCE_OBJ,
    ALREADY_FENCED,
    NO_OR_INVALID_ARGS,
    FENCE_NOT_FOUND,
}

export enum iOSPlatformEvents {
    FOREGROUND_WITH_EXISTING_FENCES = 100,
}

export enum AndroidPlatformEvents {
    ANDROID_FAILED_PARSING_INTENT_EXTRAS = 200,
    ANDROID_METHOD_UNAVAILABLE_API_VER,
    ANDROID_FAILED_PACK_INTENT
}
